"""empty message

Revision ID: 3b27963fb6e6
Revises: None
Create Date: 2015-11-22 22:17:39.717248

"""

# revision identifiers, used by Alembic.
revision = '3b27963fb6e6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('interruption', sa.Integer(), nullable=True),
    sa.Column('delta_time', sa.Integer(), nullable=True),
    sa.Column('activity', sa.String(length=128), nullable=True),
    sa.Column('comments', sa.String(length=256), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    ### end Alembic commands ###
